[package]
name = "doapi"
version = "0.1.0"
authors = ["Kevin K. <kbknapp@gmail.com>"]
description = "A wrapper library for the DigitalOcean API v2"
license = "MIT"
repository = "https://github.com/kbknapp/doapi-rs.git"
documentation = "http://kbknapp.github.io/doapi-rs"
readme = "README.md"
keywords = ["do", "lib", "digitalocean", "digital", "ocean"]

[dependencies]
hyper = "*"
serde = { git = "https://github.com/kbknapp/serde" }
serde_macros = { git = "https://github.com/kbknapp/serde_macros" }
regex = "*"

[features]
default = []

debug = []
unstable = []
